FORMAT: A1
# 6by3 API


# Group Current user endpoint

## Current user endpoint [/api/v1/user]

+ Parameters
  + include

### Get current [GET]

+ Request Responds with 200 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzY5MDQwODMsInN1YiI6NX0.Iu5kCjJvIg83Uy2-HvVB1p-8qDAfCUS_Lo8gjxBzU_Q

+ Response 200 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "id": "5",
            "type": "users",
            "attributes": {
              "email": "kenia@kessler.us"
            }
          },
          "jsonapi": {
            "version": "1.0"
          }
        }

+ Request Responds with 401 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

+ Response 401 (text/html)

    + Headers

        Content-Type: text/html

# Group Generate user token

## Generate user token [/api/v1/user/tokens]

+ Parameters
  + email (required) - Data attributes email
  + password - Data attributes password

### Generate user token [POST]

+ Request Responds with 201 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "attributes": {
              "email": "quentin@christiansengusikowski.name",
              "password": "tPBYjHyRCtPQq"
            }
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzY5MDQwODMsInN1YiI6NH0.p_Klk1flnEbeKZaFzVH8zUYgz63l-e7KQz2SdZZrYQ0"
        }

+ Request Responds with 404 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "attributes": {
              "email": "tracee@schultzmarquardt.biz",
              "password": "_RS2vWfkHgOm2"
            }
          }
        }

+ Response 404 (text/html)

    + Headers

        Content-Type: text/html

# Group Users endpoint

## Users endpoint [/api/v1/users]

+ Parameters
  + type (required) - Data type
  + email (required) - Data attributes email
  + password - Data attributes password
  + password_confirmation - Data attributes password confirmation

### Create user [POST]

+ Request Responds with 201 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "type": "users",
            "attributes": {
              "email": "denisha.watsica@kohlerdonnelly.ca",
              "password": "TpvQ7ROB6sppGRK",
              "password_confirmation": "TpvQ7ROB6sppGRK"
            }
          }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "id": "3",
            "type": "users",
            "attributes": {
              "email": "denisha.watsica@kohlerdonnelly.ca"
            }
          },
          "jsonapi": {
            "version": "1.0"
          }
        }

+ Request Responds with 409 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "type": "users",
            "attributes": {
              "email": "latisha.steuber@kiehn.info",
              "password": "zRw6XoQ0CbSXZ2L",
              "password_confirmation": "zRw6XoQ0CbSXZ2L"
            }
          }
        }

+ Response 409 (text/html)

    + Headers

        Content-Type: text/html

+ Request Responds with 422 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "type": "users",
            "attributes": {
              "email": "caryn_mckenzie@deckow.com",
              "password": null,
              "password_confirmation": null
            }
          }
        }

+ Response 422 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "errors": [
            {
              "title": "Invalid password",
              "detail": "must be filled",
              "source": {
                "pointer": "/data/attributes/password"
              }
            },
            {
              "title": "Invalid password",
              "detail": "size cannot be less than 6",
              "source": {
                "pointer": "/data/attributes/password"
              }
            }
          ],
          "jsonapi": {
            "version": "1.0"
          }
        }
