FORMAT: A1
# 6by3 API


# Group Current user endpoint

## Current user endpoint [/api/v1/user]

+ Parameters
  + include

### Get current [GET]

+ Request Responds with 200 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzQ5MzU1NDYsInN1YiI6NX0.PJQoiax-q_ig_gx6MAFnjyKZeFj95g9XdN-JnnEq8I0

+ Response 200 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "id": "5",
            "type": "users",
            "attributes": {
              "email": "paris_kassulke@schulist.us"
            }
          },
          "jsonapi": {
            "version": "1.0"
          }
        }

+ Request Responds with 401 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

+ Response 401 (text/html)

    + Headers

        Content-Type: text/html

# Group Generate user token

## Generate user token [/api/v1/user/tokens]

+ Parameters
  + email (required) - Data attributes email
  + password - Data attributes password

### Generate user token [POST]

+ Request Responds with 201 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "attributes": {
              "email": "marget@dietrichwuckert.name",
              "password": "Urt4zXADX2_"
            }
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzQ5MzU1NDUsInN1YiI6MX0.mLo--6dCm5HsvywWNbcoccfKsVIZNyLilNscC2qiq18"
        }

+ Request Responds with 404 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "attributes": {
              "email": "vanita@bartellschmeler.us",
              "password": "fBH6seOXSfu"
            }
          }
        }

+ Response 404 (text/html)

    + Headers

        Content-Type: text/html

# Group Users endpoint

## Users endpoint [/api/v1/users]

+ Parameters
  + type (required) - Data type
  + email (required) - Data attributes email
  + password - Data attributes password
  + password_confirmation - Data attributes password confirmation

### Create user [POST]

+ Request Responds with 201 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "type": "users",
            "attributes": {
              "email": "evalyn@ankundingstreich.name",
              "password": "0BnIc3h0t6oaHNV",
              "password_confirmation": "0BnIc3h0t6oaHNV"
            }
          }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "id": "4",
            "type": "users",
            "attributes": {
              "email": "evalyn@ankundingstreich.name"
            }
          },
          "jsonapi": {
            "version": "1.0"
          }
        }

+ Request Responds with 409 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "type": "users",
            "attributes": {
              "email": "josie.cummerata@jacobischaden.info",
              "password": "pWmUq3OwFq6XC3",
              "password_confirmation": "pWmUq3OwFq6XC3"
            }
          }
        }

+ Response 409 (text/html)

    + Headers

        Content-Type: text/html

+ Request Responds with 422 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "data": {
            "type": "users",
            "attributes": {
              "email": "hye@mullershields.us",
              "password": null,
              "password_confirmation": null
            }
          }
        }

+ Response 422 (application/vnd.api+json)

    + Headers

        Content-Type: application/vnd.api+json

    + Body

        {
          "errors": [
            {
              "title": "Invalid password",
              "detail": "must be filled",
              "source": {
                "pointer": "/data/attributes/password"
              }
            },
            {
              "title": "Invalid password",
              "detail": "size cannot be less than 6",
              "source": {
                "pointer": "/data/attributes/password"
              }
            }
          ],
          "jsonapi": {
            "version": "1.0"
          }
        }
