version: '3'
services:
  db:
    image: postgres:10.3
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data

  app: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash
    volumes:
      - .:/app
      - bundler-data:/usr/local/bundle/:cached
      - bin-data:/usr/local/bin/:cached
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    depends_on:
      - db
      - redis

  api:
    <<: *app
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    environment:
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-0}
    ports:
      - "3001:3001"

  redis:
    image: redis:alpine

  sidekiq:
    <<: *app
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  bundler-data:
  bin-data:
  pg-data:
