env: production 
cluster:
lb_target_group_arn:
ecs_lb_role: production_ecs_lb_role
backend_image_name:
backend_image_repository:
nginx_image_name:
nginx_image_repository:
task_role_arn:
nginx_cpu: 64
nginx_memory: 64
backend_cpu: 384
backend_desired_count: 2
backend_memory: 1024
background_cpu: 384
background_desired_count: 1
background_memory: 1024
run_command_cpu: 256
run_command_memory: 768
