env: staging
aws_region: us-east-1
cluster: six-by-three-staging
backend_image_name: 6by3-backend
backend_image_repository: 328211036245.dkr.ecr.us-east-1.amazonaws.com/6by3-backend
nginx_image_name: 6by3-nginx
nginx_image_repository: 328211036245.dkr.ecr.us-east-1.amazonaws.com/6by3-nginx
task_role_arn: arn:aws:iam::328211036245:role/ecs/six-by-three-staging_default_task
nginx_cpu: 64
nginx_memory: 64
backend_cpu: 384
backend_memory: 768
backend_desired_count: 1
background_cpu: 384
background_memory: 768
background_desired_count: 1
run_command_cpu: 256
run_command_memory: 512
