default: &default
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production: &production
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL') %>

staging:
  <<: *production
